### ISSUE TITLE
Add CI/CD Testing

### ISSUE THREAD

**Issue by stanleyowen** [stanleyowen/loofi#127]
### Problem Description

Sometimes when users commit changes to GitHub, it would probably run on local however they could fail in production.

### Solution/Idea

Therefore, it is necessary to include CI/CD to make sure that the build is working appropriately without any error or disruption.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Use CI/CD Testing | Must |

### LoFi Player Version

v0.6.4

### Operating System Version

Windows 11 Version 21H2 (Build 22000.194)

**Comment by stanleyowen** [comment]
Hello @kimlimjustin, could you please work on this issue?

**Comment by kimlimjustin** [comment]
Okay, I'll work on it tomorrow :)

**Comment by stanleyowen** [comment]
Got it, I am looking forward this!
