### ISSUE TITLE
Move .env to .env.example

### ISSUE THREAD

**Issue by Muky-dev** [stanleyowen/loofi#179]
### Problem Description

# Problem
The `.env` file is being used as `.env.example` file.

### Solution/Idea

# Sugestion 
A good practice is to have a `.env.example` as a "boilerplate" of env file and keep `.env` on gitignore, as people download the project and going to use, they put info on your own `.env` file.

### Alternatives

This is all!

### LoFi Player Version

v1.0.0-beta

### Operating System Version

Windows 10

**Comment by stanleyowen** [comment]
Hi, sorry for the late responses. I've recently updated it in the following commit: df9da0408ceaf2042b1f7f7bf7b328f71e9bf293 which will take changes in the next releases. Feel free to comment if you think I misunderstood it :)

Thankyou!
