### ISSUE TITLE
App Size is too Big

### ISSUE THREAD

**Issue by stanleyowen** [stanleyowen/loofi#98]
**Describe the bug**
When comes to the app bundle size, I think it was too big for a simple app which has `~170mb` bundle size.

**To Reproduce**
1. Clone the repo
2. Run `yarn build:electron`
3. See error

**Expected behavior**
App should be minimized if possible.

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 2009 (Build 22000.194)
 - Browser Chrome
 - Version 93.0.4577.82

**Comment by stanleyowen** [comment]
@kimlimjustin can you work on this issue?

**Comment by kimlimjustin** [comment]
Opened a PR for this, #99 :)
